# Generated by Django 2.0.4 on 2018-06-14 09:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20180614_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='Published Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.RenameModel(
            old_name='Ans',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='Quiz',
            new_name='Question',
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-publishing_date', 'id'], 'verbose_name_plural': 'Questions'},
        ),
    ]
