# Generated by Django 2.0.4 on 2018-06-10 10:02

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=11, verbose_name='Phone Number')),
                ('sex', models.CharField(blank=True, max_length=1, verbose_name='Sex')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Description')),
                ('birth', models.DateField(blank=True, verbose_name='Birth Date')),
                ('city', models.CharField(default='', max_length=100)),
                ('profile_photo', models.ImageField(blank=True, upload_to=accounts.models.upload_to, verbose_name='Profile Photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'User Informations',
            },
        ),
    ]
