# Generated by Django 2.0.4 on 2018-06-10 10:23

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180610_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(default='media/profile_photo/default_user.jpg', null=True, upload_to=accounts.models.upload_to, verbose_name='Profile Photo'),
        ),
    ]
